### PR TITLE
Banner Home Page

### PR DESCRIPTION
**Pull request by miguel-merlin**
@ShawnAviles I think you have more experience in Tailwind. Can you help me fix the spacing issues in the Home page banner.

It currently looks like this:
image

The Home template is in ```src/_includes/_layouts/Home.jsx```

### CODE REVIEW

**Comment by miguel-merlin** [comment]
#94

**Comment by ShawnAviles** [comment]
On it 🫡

**Comment by ShawnAviles** [comment]
New Hero Section Banner
image

Note: Responsiveness is not directly handled yet. Will be handled in #86

**Review by Caposto — APPROVED** [review]
sheeesh

**Comment by miguel-merlin** [comment]
Thanks!!

**Pull request merged**
