### PR TITLE
feature(navbar): Implemented and added navbar to templates

### PR DESCRIPTION
**Pull request by miguel-merlin**

### CODE REVIEW

**Comment by ezrizhu** [comment]
While you're there, could you also add footers to the templates?

**Comment by miguel-merlin** [comment]
I did in the last pr

**Comment by ezrizhu** [comment]
for the project page and the about page?

**Comment by miguel-merlin** [comment]
Yep
https://github.com/stevensblueprint/blueprint_website/blob/main/src/_includes/_layouts/Projects.jsx#L87C1-L87C24
https://github.com/stevensblueprint/blueprint_website/blob/main/src/_includes/_layouts/About.jsx#L144

**Comment by ezrizhu** [comment]
Ah, I see, the branch was outdated so I didn't see the latest changes.

**Review by ezrizhu — APPROVED** [review]

**Pull request merged**
