### PR TITLE
Removed bg images for smaller screens on homepage and centered text

### LINKED ISSUE #194: Fix spacing when reducing screen size

### PR DESCRIPTION
**Pull request by co16661666**

### CODE REVIEW

**Review by Caposto — CHANGES_REQUESTED** [review]
Changes look good! Just one small thing, for this and future Pull Requests can you include images of what the changes look like?

**Comment by co16661666** [comment]
Got it!
image

**Review by ShawnAviles — APPROVED** [review]
Tested locally and looks great! 👍

**Comment by ShawnAviles** [comment]
I think this PR is good, but overall do we want no art on the homepage when mobile users visit our site? I feel like we should at least have something... even if it is just mobile specific hero art @audreyyoo @Caposto

**Comment by audreyyoo** [comment]
> I think this PR is good, but overall do we want no art on the homepage when mobile users visit our site? I feel like we should at least have something... even if it is just mobile specific hero art @audreyyoo @Caposto

@ShawnAviles @Caposto i think that could be a good idea. just from looking at the preview provided i see a lamp hanging from the nav bar lol was that intentional? we can add clipart either around there (like on top) or below the buttons.

**Review by Caposto — APPROVED** [review]

**Pull request merged**
