### PR TITLE
Feature/about us - Changed layout to better match figma design

### LINKED ISSUE #162: Mission - About Us
This ticket concerns the section on the top of the Mission page:

Image

We would like to add some clip-art or designs to fill in the white space (blue section to the right).

### PR DESCRIPTION
**Pull request by ZhaoYuLL**
Closes #162 
Changed website layout to better match figma design
Made component mobile responsive

# Reference
image

[Figma Mockup](https://www.figma.com/design/Zw1lNlwMEahJCcN5X2L0WT/Blueprint-Website-Redesign-2024?node-id=1-2&t=UuS4hMPPksrS9y63-0)

# Desktop View
image

# Mobile View
image

### CODE REVIEW

**Review by ShawnAviles — CHANGES_REQUESTED** [review]
Nice job! Just got some points that should be addressed before we merge:

- I think for the mobile view the side padding should be made a bit smaller and the text should be larger -- so that it's readable on a phone. Currently the whole view looks like this but we need to fix the rest of the page too. 
  Screenshot 2024-08-10 at 7 03 02 PM

- Can we adjust the padding on the right side of the image so that the left and right padding of the overall content are the same. Currently it's uneven with the space between the image and right edge is larger than the spacing between the left edge and the text. I know the mockups current have the uneven spacing too but I think that was unintentional

Overall, good work. just comes down to some padding and text size changes.

**Comment by ShawnAviles** [comment]
@audreyyoo Question on the mockup, was the padding on the left and right of the content intentional? As the right padding is slightly larger than the left in the about us section

**Comment by audreyyoo** [comment]
> @audreyyoo Question on the mockup, was the padding on the left and right of the content intentional? As the right padding is slightly larger than the left in the about us section

Probably not, it might be a spacing error on my part. spacings should be even.

**Comment by ShawnAviles** [comment]
> Probably not, it might be a spacing error on my part. spacings should be even.

All good! Just wanted to confirm. Also, thank you for the quick response 🫡

**Pull request closed without merging**
