### PR TITLE
Feat/updated sponsers to figma

### PR DESCRIPTION
**Pull request by mpate154**

### CODE REVIEW

**Comment by Caposto** [comment]
@mpate154 are you able to include screenshots of what the changes look link the issue on the project board for the PR?

**Comment by mpate154** [comment]
Screenshot 2024-10-15 132759

**Review by ShawnAviles — CHANGES_REQUESTED** [review]
Overall this is great! However, I did notice that the sponsors isn't centered with the centered button in the previous section or the title of the text below it. I think this is due to the Notion logo being a square but the Github logo that we are using isn't a rectangle with some awkward white space to the left and right. Can you use a square Github Logo here instead?

**Comment by mpate154** [comment]
image

**Comment by mpate154** [comment]
I also added some bottom padding to the sponsers section and increased the overall sections width to account for it because it looked a little close to the "apply" title

**Review by ShawnAviles — APPROVED** [review]
Nice job! Looks good. You are good to squash and merge 🚀

**Pull request merged**
