### PR TITLE
added placeholder for construction

### LINKED ISSUE #154: Blog - Page Under Construction
While blog page is under construction it should show that isntead of incomplete blog.

### PR DESCRIPTION
**Pull request by Caposto**
**Related Issue:** #154 

Added placeholder to blog until its complete.

image

### CODE REVIEW

**Review by ShawnAviles — CHANGES_REQUESTED** [review]
Is there a reason that the blueprint logo is separated from the `blueprint` text. We should probably move that together so that it's consistent with the navbar and other brand assets.

**Comment by ShawnAviles** [comment]
Is the logo stretched or is that just the image? maybe we could center the logo on top of the message too

**Comment by miguel-merlin** [comment]
> Is the logo stretched or is that just the image? maybe we could center the logo on top of the message too

+1 on the stretched logo

**Comment by Caposto** [comment]
Fixed logo stretch, keeping it left aligned like the Google 404 lol\

image

**Review by ShawnAviles — APPROVED** [review]
> Fixed logo stretch, keeping it left aligned like the Google 404 lol

Ah, i see what you mean but that works for their 404 because they have the image on the right lol. So it is a aligned in the center of the page with left and right content present.

But for us, we only have left aligned content in the center of the page so it is slightly off putting. We can defer to designers @audreyyoo @sahanaali if we want some type of clip art their too

Regardless, in favor of bias for action 💯 , I think it's good to merge now

**Pull request merged**
