### PR TITLE
Mobile Responsiveness for About and Project Page

### PR DESCRIPTION
**Pull request by ShawnAviles**
# Description 

Adding mobile responsiveness for:
- About page
- Project page
- Card components
- Carousel component

**Note:**  The header and footer components will need to be updated next.

# 

Before:
Screenshot 2024-02-07 at 10 29 11 AM

After:
Screenshot 2024-02-08 at 4 17 16 PM

Only a preview of some of the changes there are a lot more.

Related to #86

### CODE REVIEW

**Review by Caposto — COMMENTED** [review]
Projects Page Footer isn't at bottom of screen: stack project cards

**Comment by ShawnAviles** [comment]
Updated Project Cards on Project Page to stack to fill full width when screen width shrinks.
Screenshot 2024-02-09 at 9 31 54 AM

**Review by miguel-merlin — APPROVED** [review]
Looks solid!

**Comment by miguel-merlin** [comment]
Merged

**Pull request merged**
